resolver: lts-20.13
packages:
- .
# Dependency packages to be pulled from upstream that are not in the resolver.
# These entries can reference officially published versions as well as
# forks / in-progress versions pinned to a git hash. For example:
#
extra-deps:
- language-docker-12.1.0@sha256:f95c2ddc9a8a5cf844e3788e8860ca0b1a142deddb4535072c3da4eacd6febd8,4075